[package]
name = "pqc-signcrypt"
version = "0.1.0"
edition = "2021"

[dependencies]
lockstitch = "0.25.2"
pqcrypto = { version = "0.17.0", default-features = false, features = ["pqcrypto-kyber", "pqcrypto-dilithium"] }

[workspace]
members = ["benchmarks"]
